app = "typesense-billowing-smoke-4667"
primary_region = "lhr"

[build]
image = "typesense/typesense:27.1"

[env]
TYPESENSE_DATA_DIR = "/data"
TYPESENSE_ENABLE_CORS = "true"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8_108
min_machines_running = 0
processes = [ "app" ]

[[mounts]]
destination = "/data"
source = "typesense_data"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "2gb"